version: "3"
   
services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'librarydb'
      MYSQL_USER: "${USER}"
      MYSQL_PASSWORD: "${PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${PASSWORD}"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./dblib:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  django:
    build: .
    command: bash -c "python3 library/manage.py migrate &&
                      python3 library/manage.py runserver 0.0.0.0:8000"
    container_name: "django-library"
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: #links: 
      - db
  vue:
    build: ./frontend
    image: vueapp:0.0.1
    container_name: "vue-app"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: #links:
      - django
volumes:
  dblib:
